name: my-first-workflow
on: push
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: runing single command on job1
        run: echo "Hi This is my first workflow"
      - name: checking os version of runing host
        run:  cat/etc/os-release
        
