name: my-first-workflow
on: push
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: runing single command on job1
        run: echo "Hi This is my first workflow"
      - name: checking os version of runing host
        run:  cat /etc/os-release
  job2:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - name: Checking Host Name
        run: hostname
      - name: Runing Multiple Command
        run: |
          echo "Hi From DS"
          echo "Current date/time is `date`"
          sleep 20
  Job3:
    name: Job3
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Runing Single Step
        run: sleep 10
  job4:
    name: job4
    needs: [job1,job2,Job3]
    runs-on: ubuntu-latest
    steps:
      - name: Ruing after Completed all job
        run: echo "Job 4 completed on `date`"
        
