name: my-second-workflow
on: push
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: step-2 - Checkout
        uses: actions/checkout@v6.0.2
      - name: Step-3
        run: |
          echo `pws` >> myartifact.txt
          ls -ltr
          hostname
      - name: upload singlr file
        uses: actions/upload-artifact@v7
        with:
          name: singlefile
          path: ./myartifact.txt
      
      

