name: my-second-workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      
    
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: step-2 - Checkout
        uses: actions/checkout@v6.0.2
      - name: Step-3
        run: |
          echo `pwd` >> myartifact.txt
          echo "this is test file" >> test.txt
          mkdir artifacts
          echo `ls -ltr` >> artifacts/list.txt
          echo `hostname` >> artifacts/hostname.txt
          
      - name: upload singlr file
        uses: actions/upload-artifact@v7
        with:
          name: singlefile
          path: ./myartifact.txt
      - name: Upload Directory
        uses: actions/upload-artifact@v7
        with:
          name: directory_artifact
          path: artifacts/
      - name: upload from multiple path with exclusion
        uses: actions/upload-artifact@v7
        with:
          name: multiplepath_with_exclusion
          path: |
            ./myartifact.txt
            ./test.txt
            artifacts/
            !**/hostname.txt
  job2:
    name: job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: checking current directory
        run: |
          pwd
          ls -ltr
      - name: Download Single file artifact
        uses: actions/download-artifact@v8
        with:
          name: singlefile
      - name: check after download
        run: |
          pwd
          ls -ltr
  job3:
    name: job3
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download directory artifact
        uses: actions/download-artifact@v8
        with:
          name: directory_artifact
      - name:  verify directory download
        run: |
          pwd
          ls -ltr
  job4:
    name: job4
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Create folder for download artifact
        run: |
          mkdir -p singlrfileArtifact
          mkdir -p directoryArtifact
      - name: Download Sigle Artifact in folder
        uses: actions/download-artifact@v8
        with:
          name: singlefile
          path: singlrfileArtifact
      - name: Download Directory in Folder
        uses: actions/download-artifact@v8
        with:
          name: directory_artifact
          path: directoryArtifact
      - name: Vrify Download
        run: |
         echo "Single File Artifact"
         ls -ltr singlrfileArtifact
         echo "Directory Artifact"
         ls -ltr directoryArtifact
    
    
        
      
      

